[package]
name = "binius_ntt"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
assert_matches.workspace = true
binius_field = { path = "../field" }
p3-util.workspace = true
rand.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion.workspace = true

[lib]
bench = false

[[bench]]
name = "additive_ntt"
harness = false

