stages:
  - lint
  - build
  - test

cargofmt:
  tags:
    - frobenius
  stage: lint
  script:
    - cargo fmt --check

clippy:
  tags:
    - frobenius
  stage: lint
  script:
    - cargo clippy --all --all-features -- -D warnings

build-debug:
  tags:
    - frobenius
  stage: build
  script:
    - RUSTFLAGS="-C target-cpu=native" cargo build --tests --benches
  artifacts:
    paths:
      - target/debug
    expire_in: 1 day

unit-test:
  tags:
    - frobenius
  stage: test
  script:
    - RUSTFLAGS="-C target-cpu=native" cargo test
