stages:
  - lint
  - build
  - test
  - deploy

cargofmt:
  tags:
    - binius
  stage: lint
  script:
    - cargo fmt --check

clippy:
  tags:
    - binius
  stage: lint
  script:
    - cargo clippy --all --all-features --tests --benches --examples -- -D warnings

build-debug:
  tags:
    - binius
  stage: build
  script:
    - cargo build --tests --benches --examples
  artifacts:
    paths:
      - target/debug
    expire_in: 1 day

unit-test:
  tags:
    - binius
  stage: test
  script:
    - cargo test

unit-test-single-threaded:
  tags:
    - binius
  stage: test
  script:
    - RAYON_NUM_THREADS=1 cargo test

unit-test-native:
  tags:
    - binius
  stage: test
  script:
    - RUSTFLAGS="-C target-cpu=native" cargo test

build-docs:
  tags:
    - binius
  stage: build
  script:
    - export RUSTDOCFLAGS=-Dwarnings
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 1 week

pages:
  tags:
    - binius
  stage: deploy
  dependencies:
    - build-docs
  script:
    - mv target/doc public
  artifacts:
    paths:
      - public
  only:
    refs:
      - tags
    variables:
      - /^v?\d+\.\d+\.\d+$/ # only version tags such as v1.0.0 or 1.0.0
