variables:
  CARGO_HOME: "$CI_PROJECT_DIR/cargo"

stages:
  - lint
  - build
  - test
  - deploy

# AMD job configuration template
.job_template_amd:
  image: rustlang/rust:nightly
  variables:
    KUBERNETES_NODE_SELECTOR_INSTANCE_TYPE: "ulvt-node-pool=ulvt-c6i-large"
  tags:
    - k8s

# ARM job configuration template
.job_template_arm:
  image: rustlang/rust:nightly
  variables:
    KUBERNETES_NODE_SELECTOR_INSTANCE_TYPE: "ulvt-node-pool=ulvt-t4g-large"
    KUBERNETES_NODE_SELECTOR_ARCH: 'kubernetes.io/arch=arm64'
  before_script:
    - if [ "$(uname -m)" != "aarch64" ]; then echo "This job is intended to run on ARM architecture only."; exit 1; fi
  tags:
    - k8s

# Linting jobs
cargofmt:
  extends: .job_template_amd
  stage: lint
  script:
    - cargo fmt --check

clippy:
  extends: .job_template_amd
  stage: lint
  script:
    - cargo clippy --all --all-features --tests --benches --examples -- -D warnings

.cached_job_template_amd:
  extends: .job_template_amd
  cache:
    key: "biniusOSS-amd-${CI_COMMIT_REF_SLUG}"
    paths:
      - target
      - cargo

.cached_job_template_arm:
  extends: .job_template_arm
  cache:
    key: "biniusOSS-arm-${CI_COMMIT_REF_SLUG}"
    paths:
      - target
      - cargo

# Building jobs
build-debug-amd:
  extends: .cached_job_template_amd
  stage: build
  script:
    - cargo build --tests --benches --examples
  artifacts:
    paths:
      - Cargo.lock
    expire_in: 1 day

build-debug-arm:
  extends: .cached_job_template_arm
  stage: build
  script:
    - cargo build --tests --benches --examples
  artifacts:
    paths:
      - Cargo.lock
    expire_in: 1 day

.test_job_template_amd:
  extends: .job_template_amd
  cache:
    key: "biniusOSS-amd-${CI_COMMIT_REF_SLUG}"
    policy: pull # do not push cache at the end to save time
    paths:
      - target
      - cargo
  dependencies:
    - build-debug-amd

.test_job_template_arm:
  extends: .job_template_arm
  cache:
    key: "biniusOSS-arm-${CI_COMMIT_REF_SLUG}"
    policy: pull # do not push cache at the end to save time
    paths:
      - target
      - cargo
  dependencies:
    - build-debug-arm

unit-test-amd:
  extends: .test_job_template_amd
  script:
    - RUST_BACKTRACE=full cargo test

unit-test-arm:
  extends: .test_job_template_arm
  script:
    - RUST_BACKTRACE=full cargo test

unit-test-single-threaded-amd:
  extends: .test_job_template_amd
  script:
    - RUST_BACKTRACE=full RAYON_NUM_THREADS=1 cargo test

unit-test-single-threaded-arm:
  extends: .test_job_template_arm
  script:
    - RUST_BACKTRACE=full RAYON_NUM_THREADS=1 cargo test

unit-test-native-amd:
  extends: .test_job_template_amd
  script:
    - RUST_BACKTRACE=full RUSTFLAGS="-C target-cpu=native" cargo test

unit-test-native-arm:
  extends: .test_job_template_arm
  script:
    - RUST_BACKTRACE=full RUSTFLAGS="-C target-cpu=native" cargo test

# Documentation and pages jobs
build-docs:
  extends: .job_template_amd
  stage: build
  script:
    - export RUSTDOCFLAGS="-Dwarnings --html-in-header doc/katex-header.html"
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 1 week

pages:
  extends: .job_template_amd
  stage: deploy
  dependencies:
    - build-docs
  script:
    - mv target/doc public
    - echo "/ /binius_core 302" > public/_redirects
  artifacts:
    paths:
      - public
  only:
    refs:
      - main # Deploy for every push to the main branch, for now

