repos:
- repo: local
  hooks:
  - id: rustfmt
    name: Run `rustfmt`
    language: rust
    types: [rust]
    entry: rustfmt
    stages: [commit]
  - id: clippy
    name: Run cargo clippy
    types: [rust]
    language: rust
    entry: cargo clippy --all --all-features --tests --benches --examples -- -D warnings
    pass_filenames: false
    stages: [push]
