[package]
name = "binius_utils"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
cfg-if.workspace = true
bytes.workspace = true
bytemuck = { workspace = true, features = ["extern_crate_alloc"] }
itertools.workspace = true
rayon.workspace = true
thiserror.workspace = true
thread_local.workspace = true

[features]
default = []
bail_panic = []
